log_path: logs
bert_model: klue/roberta-large
train_data_path: data/train.txt
val_data_path: data/val.txt
test_data_path: data/test.txt
max_len: 512
train_batch_size: 16
eval_batch_size: 16
dropout_rate: 0.1
gpus: -1
epochs: 3
task: spacing
